# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mohammad.fakhreddin/Documents/c-plus-plus-projects/openGl-3D-cube

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mohammad.fakhreddin/Documents/c-plus-plus-projects/openGl-3D-cube

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mohammad.fakhreddin/Documents/c-plus-plus-projects/openGl-3D-cube/CMakeFiles /Users/mohammad.fakhreddin/Documents/c-plus-plus-projects/openGl-3D-cube/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mohammad.fakhreddin/Documents/c-plus-plus-projects/openGl-3D-cube/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3d-cube

# Build rule for target.
3d-cube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3d-cube
.PHONY : 3d-cube

# fast build rule for target.
3d-cube/fast:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/build
.PHONY : 3d-cube/fast

mac/main.o: mac/main.cpp.o

.PHONY : mac/main.o

# target to build an object file
mac/main.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/mac/main.cpp.o
.PHONY : mac/main.cpp.o

mac/main.i: mac/main.cpp.i

.PHONY : mac/main.i

# target to preprocess a source file
mac/main.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/mac/main.cpp.i
.PHONY : mac/main.cpp.i

mac/main.s: mac/main.cpp.s

.PHONY : mac/main.s

# target to generate assembly for a file
mac/main.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/mac/main.cpp.s
.PHONY : mac/main.cpp.s

src/3d_shape/Shape3d.o: src/3d_shape/Shape3d.cpp.o

.PHONY : src/3d_shape/Shape3d.o

# target to build an object file
src/3d_shape/Shape3d.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/Shape3d.cpp.o
.PHONY : src/3d_shape/Shape3d.cpp.o

src/3d_shape/Shape3d.i: src/3d_shape/Shape3d.cpp.i

.PHONY : src/3d_shape/Shape3d.i

# target to preprocess a source file
src/3d_shape/Shape3d.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/Shape3d.cpp.i
.PHONY : src/3d_shape/Shape3d.cpp.i

src/3d_shape/Shape3d.s: src/3d_shape/Shape3d.cpp.s

.PHONY : src/3d_shape/Shape3d.s

# target to generate assembly for a file
src/3d_shape/Shape3d.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/Shape3d.cpp.s
.PHONY : src/3d_shape/Shape3d.cpp.s

src/3d_shape/edge/base_edge/BaseEdge.o: src/3d_shape/edge/base_edge/BaseEdge.cpp.o

.PHONY : src/3d_shape/edge/base_edge/BaseEdge.o

# target to build an object file
src/3d_shape/edge/base_edge/BaseEdge.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/base_edge/BaseEdge.cpp.o
.PHONY : src/3d_shape/edge/base_edge/BaseEdge.cpp.o

src/3d_shape/edge/base_edge/BaseEdge.i: src/3d_shape/edge/base_edge/BaseEdge.cpp.i

.PHONY : src/3d_shape/edge/base_edge/BaseEdge.i

# target to preprocess a source file
src/3d_shape/edge/base_edge/BaseEdge.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/base_edge/BaseEdge.cpp.i
.PHONY : src/3d_shape/edge/base_edge/BaseEdge.cpp.i

src/3d_shape/edge/base_edge/BaseEdge.s: src/3d_shape/edge/base_edge/BaseEdge.cpp.s

.PHONY : src/3d_shape/edge/base_edge/BaseEdge.s

# target to generate assembly for a file
src/3d_shape/edge/base_edge/BaseEdge.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/base_edge/BaseEdge.cpp.s
.PHONY : src/3d_shape/edge/base_edge/BaseEdge.cpp.s

src/3d_shape/edge/color_edge/ColorEdge.o: src/3d_shape/edge/color_edge/ColorEdge.cpp.o

.PHONY : src/3d_shape/edge/color_edge/ColorEdge.o

# target to build an object file
src/3d_shape/edge/color_edge/ColorEdge.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/color_edge/ColorEdge.cpp.o
.PHONY : src/3d_shape/edge/color_edge/ColorEdge.cpp.o

src/3d_shape/edge/color_edge/ColorEdge.i: src/3d_shape/edge/color_edge/ColorEdge.cpp.i

.PHONY : src/3d_shape/edge/color_edge/ColorEdge.i

# target to preprocess a source file
src/3d_shape/edge/color_edge/ColorEdge.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/color_edge/ColorEdge.cpp.i
.PHONY : src/3d_shape/edge/color_edge/ColorEdge.cpp.i

src/3d_shape/edge/color_edge/ColorEdge.s: src/3d_shape/edge/color_edge/ColorEdge.cpp.s

.PHONY : src/3d_shape/edge/color_edge/ColorEdge.s

# target to generate assembly for a file
src/3d_shape/edge/color_edge/ColorEdge.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/color_edge/ColorEdge.cpp.s
.PHONY : src/3d_shape/edge/color_edge/ColorEdge.cpp.s

src/3d_shape/edge/simple_edge/SimpleEdge.o: src/3d_shape/edge/simple_edge/SimpleEdge.cpp.o

.PHONY : src/3d_shape/edge/simple_edge/SimpleEdge.o

# target to build an object file
src/3d_shape/edge/simple_edge/SimpleEdge.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/simple_edge/SimpleEdge.cpp.o
.PHONY : src/3d_shape/edge/simple_edge/SimpleEdge.cpp.o

src/3d_shape/edge/simple_edge/SimpleEdge.i: src/3d_shape/edge/simple_edge/SimpleEdge.cpp.i

.PHONY : src/3d_shape/edge/simple_edge/SimpleEdge.i

# target to preprocess a source file
src/3d_shape/edge/simple_edge/SimpleEdge.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/simple_edge/SimpleEdge.cpp.i
.PHONY : src/3d_shape/edge/simple_edge/SimpleEdge.cpp.i

src/3d_shape/edge/simple_edge/SimpleEdge.s: src/3d_shape/edge/simple_edge/SimpleEdge.cpp.s

.PHONY : src/3d_shape/edge/simple_edge/SimpleEdge.s

# target to generate assembly for a file
src/3d_shape/edge/simple_edge/SimpleEdge.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/simple_edge/SimpleEdge.cpp.s
.PHONY : src/3d_shape/edge/simple_edge/SimpleEdge.cpp.s

src/3d_shape/edge/texture_edge/TextureEdge.o: src/3d_shape/edge/texture_edge/TextureEdge.cpp.o

.PHONY : src/3d_shape/edge/texture_edge/TextureEdge.o

# target to build an object file
src/3d_shape/edge/texture_edge/TextureEdge.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/texture_edge/TextureEdge.cpp.o
.PHONY : src/3d_shape/edge/texture_edge/TextureEdge.cpp.o

src/3d_shape/edge/texture_edge/TextureEdge.i: src/3d_shape/edge/texture_edge/TextureEdge.cpp.i

.PHONY : src/3d_shape/edge/texture_edge/TextureEdge.i

# target to preprocess a source file
src/3d_shape/edge/texture_edge/TextureEdge.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/texture_edge/TextureEdge.cpp.i
.PHONY : src/3d_shape/edge/texture_edge/TextureEdge.cpp.i

src/3d_shape/edge/texture_edge/TextureEdge.s: src/3d_shape/edge/texture_edge/TextureEdge.cpp.s

.PHONY : src/3d_shape/edge/texture_edge/TextureEdge.s

# target to generate assembly for a file
src/3d_shape/edge/texture_edge/TextureEdge.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/3d_shape/edge/texture_edge/TextureEdge.cpp.s
.PHONY : src/3d_shape/edge/texture_edge/TextureEdge.cpp.s

src/application/Application.o: src/application/Application.cpp.o

.PHONY : src/application/Application.o

# target to build an object file
src/application/Application.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/application/Application.cpp.o
.PHONY : src/application/Application.cpp.o

src/application/Application.i: src/application/Application.cpp.i

.PHONY : src/application/Application.i

# target to preprocess a source file
src/application/Application.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/application/Application.cpp.i
.PHONY : src/application/Application.cpp.i

src/application/Application.s: src/application/Application.cpp.s

.PHONY : src/application/Application.s

# target to generate assembly for a file
src/application/Application.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/application/Application.cpp.s
.PHONY : src/application/Application.cpp.s

src/fa_texture/FaTexture.o: src/fa_texture/FaTexture.cpp.o

.PHONY : src/fa_texture/FaTexture.o

# target to build an object file
src/fa_texture/FaTexture.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/fa_texture/FaTexture.cpp.o
.PHONY : src/fa_texture/FaTexture.cpp.o

src/fa_texture/FaTexture.i: src/fa_texture/FaTexture.cpp.i

.PHONY : src/fa_texture/FaTexture.i

# target to preprocess a source file
src/fa_texture/FaTexture.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/fa_texture/FaTexture.cpp.i
.PHONY : src/fa_texture/FaTexture.cpp.i

src/fa_texture/FaTexture.s: src/fa_texture/FaTexture.cpp.s

.PHONY : src/fa_texture/FaTexture.s

# target to generate assembly for a file
src/fa_texture/FaTexture.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/fa_texture/FaTexture.cpp.s
.PHONY : src/fa_texture/FaTexture.cpp.s

src/open_gl/OpenGl.o: src/open_gl/OpenGl.cpp.o

.PHONY : src/open_gl/OpenGl.o

# target to build an object file
src/open_gl/OpenGl.cpp.o:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/open_gl/OpenGl.cpp.o
.PHONY : src/open_gl/OpenGl.cpp.o

src/open_gl/OpenGl.i: src/open_gl/OpenGl.cpp.i

.PHONY : src/open_gl/OpenGl.i

# target to preprocess a source file
src/open_gl/OpenGl.cpp.i:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/open_gl/OpenGl.cpp.i
.PHONY : src/open_gl/OpenGl.cpp.i

src/open_gl/OpenGl.s: src/open_gl/OpenGl.cpp.s

.PHONY : src/open_gl/OpenGl.s

# target to generate assembly for a file
src/open_gl/OpenGl.cpp.s:
	$(MAKE) -f CMakeFiles/3d-cube.dir/build.make CMakeFiles/3d-cube.dir/src/open_gl/OpenGl.cpp.s
.PHONY : src/open_gl/OpenGl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 3d-cube"
	@echo "... mac/main.o"
	@echo "... mac/main.i"
	@echo "... mac/main.s"
	@echo "... src/3d_shape/Shape3d.o"
	@echo "... src/3d_shape/Shape3d.i"
	@echo "... src/3d_shape/Shape3d.s"
	@echo "... src/3d_shape/edge/base_edge/BaseEdge.o"
	@echo "... src/3d_shape/edge/base_edge/BaseEdge.i"
	@echo "... src/3d_shape/edge/base_edge/BaseEdge.s"
	@echo "... src/3d_shape/edge/color_edge/ColorEdge.o"
	@echo "... src/3d_shape/edge/color_edge/ColorEdge.i"
	@echo "... src/3d_shape/edge/color_edge/ColorEdge.s"
	@echo "... src/3d_shape/edge/simple_edge/SimpleEdge.o"
	@echo "... src/3d_shape/edge/simple_edge/SimpleEdge.i"
	@echo "... src/3d_shape/edge/simple_edge/SimpleEdge.s"
	@echo "... src/3d_shape/edge/texture_edge/TextureEdge.o"
	@echo "... src/3d_shape/edge/texture_edge/TextureEdge.i"
	@echo "... src/3d_shape/edge/texture_edge/TextureEdge.s"
	@echo "... src/application/Application.o"
	@echo "... src/application/Application.i"
	@echo "... src/application/Application.s"
	@echo "... src/fa_texture/FaTexture.o"
	@echo "... src/fa_texture/FaTexture.i"
	@echo "... src/fa_texture/FaTexture.s"
	@echo "... src/open_gl/OpenGl.o"
	@echo "... src/open_gl/OpenGl.i"
	@echo "... src/open_gl/OpenGl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

